trigger:
- master

pool:
   name: 'default'

steps:
# Step 1: Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Step 2: Install Dependencies
- script: |
    npm install
  displayName: 'Install Dependencies'

# Step 3: Run Tests
- script: |
    npm test
  displayName: 'Run Tests'

# Step 4: Build the Application
- script: |
    npm run build
  displayName: 'Build the Application'

# Step 5: Copy Files to Artifact Staging Directory
- script: |
    if not exist "$(Build.ArtifactStagingDirectory)" mkdir "$(Build.ArtifactStagingDirectory)"
    if exist dist (
        xcopy dist "$(Build.ArtifactStagingDirectory)" /E /I /Y
    ) else (
        echo "Error: The 'dist' directory does not exist. Check the build step."
        exit 1
    )
  displayName: 'Copy Files to Artifact Staging Directory'

# Step 6: Optional - Debugging Step
- script: |
    dir "$(Build.ArtifactStagingDirectory)"
  displayName: 'Check Files in Artifact Staging Directory'

# Step 7: Publish Build Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)' # Path where files are staged
    artifactName: 'drop'                               # Name of the artifact
    publishLocation: 'Container'                      # Default storage in Azure DevOps
  displayName: 'Publish Build Artifacts'
